vocbench:
  build: vocbench
  links:
   - vocbench-db:mysql
   - vocbench-sesame:sesame
   - vocbench-st:st
  ports:
    - "10140:8080"
  volumes: 
    - ./upload:/usr/local/tomcat/temp
vocbench-db:
  image: mariadb
  environment:
    - MYSQL_USER=vocbench
    - MYSQL_PASSWORD=ieg9ohZi
    - MYSQL_DATABASE=vocbench
    - MYSQL_ROOT_PASSWORD=changeme
vocbench-sesame:
  image: openuniversity/sesame
  ports:
   - "10150:8080"
vocbench-st:
  build: semantic-turkey
  volumes: 
    - ./upload:/usr/local/tomcat/temp
  links:
    - vocbench-sesame:sesame